#############################################################################
# Makefile for building: cuda_test
# Generated by qmake (3.0) (Qt 5.1.0) on: Mon Jun 3 16:03:56 2013
# Project:  cuda_test.pro
# Template: app
# Command: /home/heu/Qt5.1.0/5.1.0-beta1/gcc/bin/qmake -spec linux-g++ -o Makefile cuda_test.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/linux-g++ -I. -I/usr/local/cuda-5.0 -I/home/heu/NVIDIA_CUDA-5.0_Samples/common/inc -I../../../Qt5.1.0/5.1.0-beta1/gcc/include -I../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL -I../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtMultimedia -I../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets -I../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtNetwork -I../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui -I../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/heu/Qt5.1.0/5.1.0-beta1/gcc -Wl,-rpath,/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib
LIBS          = $(SUBLIBS) -L/usr/local/cuda-5.0/lib -lcudart -lcufft -lGLU -L/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib -lQt5OpenGL -lQt5Multimedia -lQt5Widgets -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/heu/Qt5.1.0/5.1.0-beta1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		myglwidget.cpp \
		waveform.cpp \
		hello.cu moc_widget.cpp \
		moc_myglwidget.cpp \
		moc_waveform.cpp
OBJECTS       = main.o \
		widget.o \
		myglwidget.o \
		waveform.o \
		hello.o \
		moc_widget.o \
		moc_myglwidget.o \
		moc_waveform.o
DIST          = ../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/spec_pre.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/shell-unix.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/unix.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/linux.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/gcc-base.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/g++-base.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/g++-unix.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/qconfig.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_clucene.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_v8.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/qt_functions.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/qt_config.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/spec_post.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/default_pre.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/default_pre.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/resolve_config.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/default_post.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/warn_on.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/qt.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/resources.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/moc.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/opengl.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/uic.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/thread.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/wayland-scanner.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/testcase_targets.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/exceptions.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/yacc.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/lex.prf \
		cuda_test.pro \
		cuda_test.pro
QMAKE_TARGET  = cuda_test
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = cuda_test


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cuda_test.pro ../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/linux-g++/qmake.conf ../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/spec_pre.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/shell-unix.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/unix.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/linux.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/gcc-base.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/g++-base.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/g++-unix.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/qconfig.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_clucene.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_v8.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/qt_functions.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/qt_config.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/spec_post.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/default_pre.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/default_pre.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/resolve_config.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/default_post.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/warn_on.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/qt.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/resources.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/moc.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/opengl.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/uic.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/thread.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/wayland-scanner.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/testcase_targets.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/exceptions.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/yacc.prf \
		../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/lex.prf \
		cuda_test.pro \
		/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5OpenGL.prl \
		/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5Multimedia.prl \
		/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5Widgets.prl \
		/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5Network.prl \
		/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5Gui.prl \
		/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile cuda_test.pro
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/spec_pre.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/shell-unix.conf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/unix.conf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/linux.conf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/gcc-base.conf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/gcc-base-unix.conf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/g++-base.conf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/common/g++-unix.conf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/qconfig.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_bootstrap.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_clucene.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_designercomponents.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_platformsupport.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_quickparticles.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_v8.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/qt_functions.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/qt_config.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/linux-g++/qmake.conf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/spec_post.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/exclusive_builds.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/default_pre.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/default_pre.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/resolve_config.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/default_post.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/warn_on.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/qt.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/resources.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/moc.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/opengl.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/uic.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/unix/thread.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/wayland-scanner.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/testcase_targets.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/exceptions.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/yacc.prf:
../../../Qt5.1.0/5.1.0-beta1/gcc/mkspecs/features/lex.prf:
cuda_test.pro:
/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5OpenGL.prl:
/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5Multimedia.prl:
/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5Widgets.prl:
/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5Network.prl:
/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5Gui.prl:
/home/heu/Qt5.1.0/5.1.0-beta1/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile cuda_test.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/cuda_test1.0.0 || mkdir -p .tmp/cuda_test1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cuda_test1.0.0/ && $(COPY_FILE) --parents widget.h myglwidget.h waveform.h submarinev3.h .tmp/cuda_test1.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp myglwidget.cpp waveform.cpp hello.cu .tmp/cuda_test1.0.0/ && $(COPY_FILE) --parents widget.ui .tmp/cuda_test1.0.0/ && (cd `dirname .tmp/cuda_test1.0.0` && $(TAR) cuda_test1.0.0.tar cuda_test1.0.0 && $(COMPRESS) cuda_test1.0.0.tar) && $(MOVE) `dirname .tmp/cuda_test1.0.0`/cuda_test1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cuda_test1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_qtwayland-client-header_make_all:
compiler_qtwayland-client-header_clean:
compiler_qtwayland-server-header_make_all:
compiler_qtwayland-server-header_clean:
compiler_moc_header_make_all: moc_widget.cpp moc_myglwidget.cpp moc_waveform.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_myglwidget.cpp moc_waveform.cpp
moc_widget.cpp: ../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QWidget \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtouchdevice.h \
		myglwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/QGLWidget \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qgl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopengl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qt_windows.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopengles2ext.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopenglext.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintengine.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainter.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtextoption.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpen.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qglcolormap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qtopenglglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QSurfaceFormat \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qsurfaceformat.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/QPoint \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QPushButton \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qpushbutton.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qicon.h \
		waveform.h \
		widget.h
	/home/heu/Qt5.1.0/5.1.0-beta1/gcc/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/i686-linux-gnu/. -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include widget.h -o moc_widget.cpp

moc_myglwidget.cpp: ../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/QGLWidget \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qgl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopengl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qt_windows.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopengles2ext.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopenglext.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtouchdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintengine.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainter.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtextoption.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpen.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qglcolormap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qtopenglglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QSurfaceFormat \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qsurfaceformat.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/QPoint \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QPushButton \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qpushbutton.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qicon.h \
		myglwidget.h
	/home/heu/Qt5.1.0/5.1.0-beta1/gcc/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/i686-linux-gnu/. -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include myglwidget.h -o moc_myglwidget.cpp

moc_waveform.cpp: ../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QWidget \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtouchdevice.h \
		waveform.h
	/home/heu/Qt5.1.0/5.1.0-beta1/gcc/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.6 -I/usr/include/c++/4.6/i686-linux-gnu/. -I/usr/include/c++/4.6/backward -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.6.1/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include waveform.h -o moc_waveform.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_qtwayland-client-code_make_all:
compiler_qtwayland-client-code_clean:
compiler_qtwayland-server-code_make_all:
compiler_qtwayland-server-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui
	/home/heu/Qt5.1.0/5.1.0-beta1/gcc/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QApplication \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qapplication.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcoreapplication.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qeventloop.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtouchdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qguiapplication.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qinputmethod.h \
		widget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QWidget \
		myglwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/QGLWidget \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qgl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopengl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qt_windows.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopengles2ext.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopenglext.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintengine.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainter.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtextoption.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpen.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qglcolormap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qtopenglglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QSurfaceFormat \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qsurfaceformat.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/QPoint \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QPushButton \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qpushbutton.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qicon.h \
		waveform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QWidget \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtouchdevice.h \
		myglwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/QGLWidget \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qgl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopengl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qt_windows.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopengles2ext.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopenglext.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintengine.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainter.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtextoption.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpen.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qglcolormap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qtopenglglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QSurfaceFormat \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qsurfaceformat.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/QPoint \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QPushButton \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qpushbutton.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qicon.h \
		waveform.h \
		ui_widget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/QVariant \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QAction \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qaction.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qactiongroup.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QApplication \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qapplication.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcoreapplication.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qeventloop.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qguiapplication.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qinputmethod.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QButtonGroup \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qbuttongroup.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QHeaderView \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qheaderview.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qabstractitemview.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qframe.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qabstractitemmodel.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qitemselectionmodel.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qabstractitemdelegate.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qstyleoption.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qabstractspinbox.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qvalidator.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qregularexpression.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qslider.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qabstractslider.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qstyle.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qtabbar.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qtabwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qrubberband.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QTextBrowser \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qtextbrowser.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qtextedit.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtextdocument.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtextcursor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtextformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

myglwidget.o: myglwidget.cpp myglwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/QGLWidget \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qgl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopengl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qt_windows.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopengles2ext.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qopenglext.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtouchdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintengine.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainter.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtextoption.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpen.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qglcolormap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtOpenGL/qtopenglglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QSurfaceFormat \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qsurfaceformat.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/QPoint \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QPushButton \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qpushbutton.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qabstractbutton.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qicon.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QWheelEvent \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/QDebug \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QPainter \
		dc10.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myglwidget.o myglwidget.cpp

waveform.o: waveform.cpp waveform.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QWidget \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qwidget.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobal.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qconfig.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfeatures.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsystemdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcompilerdetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qprocessordetection.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qglobalstatic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qgenericatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_msvc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_integrity.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qoldbasicatomic.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_vxworks.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_power.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_alpha.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv7.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv6.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_armv5.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_bfin.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_ia64.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_mips.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_s390.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sh4a.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_sparc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_x86.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_cxx11.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_gcc.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qatomic_unix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmutex.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlogging.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qflags.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypeinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtypetraits.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsysinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qnamespace.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qwindowdefs_win.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstring.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qchar.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qbytearray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrefcount.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qarraydata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringbuilder.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qalgorithms.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiterator.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcoreevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qscopedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmetatype.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvarlengtharray.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontainerfwd.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qisenum.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qobject_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmargins.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qrect.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsize.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpoint.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpaintdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpalette.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcolor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qrgb.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringlist.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdatastream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qiodevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qpair.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qregexp.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qstringmatcher.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qbrush.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvector.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qmatrix.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpolygon.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qregion.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qline.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtransform.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainterpath.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qimage.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpixmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qshareddata.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qhash.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfont.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontmetrics.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qfontinfo.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qsizepolicy.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qcursor.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qkeysequence.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qevent.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qvariant.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qmap.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qdebug.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtextstream.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qlocale.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qset.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qcontiguouscache.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurl.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qurlquery.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfile.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qfiledevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qvector2d.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtouchdevice.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QPainter \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpainter.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qtextoption.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/qpen.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/QMessageBox \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qmessagebox.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtWidgets/qdialog.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QMouseEvent \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QWheelEvent \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtGui/QPainterPath \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/QTextCodec \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/qtextcodec.h \
		../../../Qt5.1.0/5.1.0-beta1/gcc/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waveform.o waveform.cpp

hello.o: hello.cu 
	$(CC) -c $(CFLAGS) $(INCPATH) -o hello.o hello.cu

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_myglwidget.o: moc_myglwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myglwidget.o moc_myglwidget.cpp

moc_waveform.o: moc_waveform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_waveform.o moc_waveform.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

